### ISSUE TITLE
Incorrectly strips description from Background section

### ISSUE THREAD

**Issue by dnwe** [muhqu/gherkinfmt#4]
If you have a description on your Background: section, for example:

``` gherkin
Feature: Sales

  Background: already completed a sale
    Given a $100 microwave was sold on 2015-11-03
    And today is 2015-11-18
```

When you run this through gherkinfmt, it succeeds but the output has incorrectly had the 'already completed a sale' description silently removed.

**Comment by muhqu** [comment]
@dnwe thanks for filing the issue! …it should be fixed with the latest version [v1.0.1](https://github.com/muhqu/gherkinfmt/releases/tag/v1.0.1)
